#!/bin/sh
export WINEPREFIX="$HOME/.wine_osu"
export STAGING_AUDIO_DURATION=10000 
export PATH=/opt/wine-osu/bin:$PATH
export osupath='/home/sgtxn/.wine_osu/drive_c/users/sgtxn/osu'
cd $osupath 
if ! mountpoint -q $osupath/Songs; then
    sudo mount /dev/sda2 $osupath/Songs
fi
notify-send "DUNST_COMMAND_PAUSE"
wine osu!.exe "$@"
sudo umount $osupath/Songs
notify-send "DUNST_COMMAND_RESUME"
