#!/usr/bin/bash

# ------------------Variables-----------------

PCHOST='sgt'
LAPTOPHOST='sgtxn-laptop'

# ----------------Shared startup--------------

shared_startup() {
    sxhkd &
    nitrogen --restore &
    telegram-desktop &
    discord &
    xsetroot -cursor_name left_ptr &
    xset r rate 350 60 &
    nm-applet &
    # picom -b --experimental-backends &
}

# --------------Main PC startup---------------

pc_startup() {
    steam -silent &
}

# --------------Laptop startup----------------

laptop_startup() {
    echo "yay"
}

# ---------- Conditional Startups-------------

if ! pgrep "polybar" > /dev/null 2>&1 ; then
    ~/.config/polybar/launch.sh &
fi

if ! pidof "firefox" > /dev/null 2>&1 ; then
    firefox &
fi

if ! pgrep "redshift-gtk" > /dev/null 2>&1 ; then
    redshift-gtk &
fi

# --------------Shared config-----------------

pc_bspwm_config() {
    bspc monitor DP-0  -n 0 -d 1 2 3 4 5 6 7 
    bspc monitor HDMI-0 -n 1 -d 8 9
    bspc config border_radius               0 
    bspc config border_width                3
    bspc config window_gap			        8	
    bspc config top_padding			        33	
    bspc config pointer_motion_interval     5ms
}

shared_bspwm_config() {
    bspc config bottom_padding		        0
    bspc config left_padding		        0
    bspc config right_padding		        0
    bspc config click_to_focus              true
    bspc config split_ratio                 0.55
    bspc config single_monocle              true
    bspc config borderless_monocle          true
    bspc config gapless_monocle             true
    bspc config focus_by_distance           true
    bspc config focus_follows_pointer       true
    bspc config history_aware_focus         true
    #bspc config honor_size_hints           true
    #bspc config top_monocle_padding		10
    #bspc config right_monocle_padding	    50
    #bspc config bottom_monocle_padding	    10
    #bspc config left_monocle_padding	    50
    bspc config pointer_modifier 		    mod4
    bspc config pointer_action1 		    move
    bspc config pointer_action2 		    resize_side
    bspc config pointer_action3 		    resize_corner
    bspc config automatic_scheme            longest_side

    bspc config normal_border_color	       "#4c566a"
    #bspc config active_border_color       "#81a1c1"
    bspc config presel_feedback_color      "#b48ead"
    bspc config focused_border_color       "#bd93f9"
    bspc config urgent_border_color        "#dd2727"
}

shared_bspwm_rules() {
    bspc rule -a firefox desktop=2 follow=on focus=on center=on private=on
    bspc rule -a firefox:Toolkit state=floating center=false sticky=on rectangle=854x480+1692+42
    bspc rule -a TelegramDesktop desktop=3
    bspc rule -a discord desktop=3
    bspc rule -a Skype desktop=3
    bspc rule -a Lutris desktop=6 focus=on center=on private=on
    bspc rule -a code-oss desktop=1
    bspc rule -a Steam desktop=6
    bspc rule -a mpv state=floating center=on focus=on
    bspc rule -a feh state=floating center=on focus=on
    bspc rule -a Gedit state=floating center=on focus=on
    bspc rule -a Zathura state=tiled center=on focus=on
    bspc rule -a feh state=floating center=on focus=on
    bspc rule -a Nemo state=floating center=false focus=on
}

# --------------------Execute------------------

if [ $(hostname) = $PCHOST ]; then
    cat $XDG_CONFIG_HOME/sxhkd/sxhkdrc_shared $XDG_CONFIG_HOME/sxhkd/sxhkdrc_pc > $XDG_CONFIG_HOME/sxhkd/sxhkdrc 
    shared_startup
    shared_bspwm_config
    shared_bspwm_rules
    pc_startup
    pc_bspwm_config
fi

if [ $(hostname) = $LAPTOPHOST ]; then
    shared_startup
    shared_bspwm_config
    shared_bspwm_rules
    laptop_startup 
fi
