#!/usr/bin/bash

# ------------------Variables-----------------

PCHOST='sgt'
HPHOST='sgt-hp'
T440PHOST='t440p'

TOP_PADDING=30
YT_FLOAT_WIDTH=854
YT_FLOAT_HEIGHT=480
SCREEN_WIDTH=$(xdpyinfo | awk '/dimensions/{print $2}' | grep -Po "^\d+")
SCREEN_HEIGHT=$(xdpyinfo | awk '/dimensions/{print $2}' | grep -Po "\d+$")
YT_FLOAT_RECTANGLE=$YT_FLOAT_WIDTH\x$YT_FLOAT_HEIGHT+$(($SCREEN_WIDTH-$YT_FLOAT_WIDTH))+$TOP_PADDING


# ----------------Shared startup--------------

shared_startup() {
    nitrogen --restore &
    telegram-desktop &
    discord &
    xsetroot -cursor_name left_ptr &
    xset r rate 350 60 &
    nm-applet &
    wmname compiz &
    # picom -b --experimental-backends &
}

# --------------Main PC startup---------------

pc_startup() {
    steam -silent &
}

# --------------Laptop startup----------------

laptop_startup() {
    libinput-gestures-setup start
}

# ---------- Conditional Startups-------------

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x "polybar" > /dev/null || ~/.config/polybar/launch.sh &
pidof "firefox" > /dev/null || firefox &
pgrep "redshift-gtk" > /dev/null || redshift-gtk &

# --------------Shared config-----------------

pc_bspwm_config() {
    bspc monitor -n 0 -d code web chat work media vidya extra 
    bspc monitor HDMI-0 -n 1 -d 8 9
    bspc config window_gap			        8	
    bspc config pointer_motion_interval     4ms
}

laptop_bspwm_config() {
    bspc monitor -n 0 -d code web chat work media vidya extra 
    bspc monitor HDMI1 -n 1 -d 8 9
    bspc config window_gap			        0	
    bspc config pointer_motion_interval     8ms
}

shared_bspwm_config() {
    bspc config top_padding			        $TOP_PADDING	
    bspc config bottom_padding		        0
    bspc config left_padding		        0
    bspc config right_padding		        0
    bspc config border_radius               0 
    bspc config border_width                3
    bspc config click_to_focus              true
    bspc config split_ratio                 0.55
    bspc config single_monocle              true
    bspc config borderless_monocle          true
    bspc config gapless_monocle             true
    bspc config focus_by_distance           true
    bspc config focus_follows_pointer       true
    bspc config history_aware_focus         true
    #bspc config honor_size_hints           true
    #bspc config top_monocle_padding		10
    #bspc config right_monocle_padding	    50
    #bspc config bottom_monocle_padding	    10
    #bspc config left_monocle_padding	    50
    bspc config pointer_modifier 		    mod4
    bspc config pointer_action1 		    move
    bspc config pointer_action2 		    resize_side
    bspc config pointer_action3 		    resize_corner
    bspc config automatic_scheme            longest_side

    bspc config normal_border_color	       "#4c566a"
    #bspc config active_border_color       "#81a1c1"
    bspc config presel_feedback_color      "#b48ead"
    bspc config focused_border_color       "#bd93f9"
    bspc config urgent_border_color        "#dd2727"
}

shared_bspwm_rules() {
    bspc rule -a firefox desktop=web follow=on focus=on center=on private=on
    bspc rule -a firefox:Toolkit state=floating center=false sticky=on rectangle=$YT_FLOAT_RECTANGLE
    bspc rule -a TelegramDesktop desktop=chat
    bspc rule -a discord desktop=chat
    bspc rule -a Skype desktop=chat
    bspc rule -a Lutris desktop=vidya focus=on center=on private=on
    bspc rule -a code-oss desktop=code
    bspc rule -a Steam desktop=vidya
    bspc rule -a mpv state=floating center=on focus=on
    bspc rule -a feh state=floating center=on focus=on
    bspc rule -a Gedit state=floating center=on focus=on
    bspc rule -a Zathura state=tiled center=on focus=on
    bspc rule -a feh state=floating center=on focus=on
    bspc rule -a "Nemo:nemo:Home" state=floating center=true focus=on rectangle=1440x900+0+0
    bspc rule -a Alacritty:term_float state=floating
}

# --------------------Execute------------------

if [ $(hostname) = $PCHOST ]; then
    cat $XDG_CONFIG_HOME/sxhkd/sxhkdrc_shared $XDG_CONFIG_HOME/sxhkd/sxhkdrc_pc > $XDG_CONFIG_HOME/sxhkd/sxhkdrc 
    shared_startup
    shared_bspwm_config
    shared_bspwm_rules
    pc_startup
    pc_bspwm_config
else
    cat $XDG_CONFIG_HOME/sxhkd/sxhkdrc_shared $XDG_CONFIG_HOME/sxhkd/sxhkdrc_laptop > $XDG_CONFIG_HOME/sxhkd/sxhkdrc 
    shared_startup
    shared_bspwm_config
    shared_bspwm_rules
    laptop_startup 
    laptop_bspwm_config
fi
