
[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "PasteSelection"
key = "V"
mods = "Alt|Shift"

[scrolling]
history = 100000
multiplier = 3

[window]
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 110
lines = 40

[window.padding]
x = 3
y = 3

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-frappe.toml"]
